<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>PHP Slim Weather App</title>
        <link rel="stylesheet" href="/css/index.css" type="text/css"/>
    </head>
    <body>
        <?php include "header.phtml"; ?>
        <h1>Demo Weather App</h1>
        <p>This is a demonstration web app for the display of weather information for a selection of cities.</p>
        <p>The weather is updated every 3 hours by a cron job which makes a request to OpenWeatherMap.</p>
        <p>This web application was written by Paul Young using Slim (a micro framework for PHP).</p>

        <div>
            <table>
                <thead>
                    <tr>
                        <td></td>
                        <?php
                        ksort($locations);

                        foreach ($locations as $id => $location) {
                            echo "<th>$location</th>";
                        }
                        ?>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($time_intervals as $intervalsAgo => $locationReadings) {
                        echo "<tr>";
                        $rowElements = [];

                        foreach ($locationReadings as $locationID => $readings) {
                            foreach ($readings as $readingID => $reading) {
                                $rowElements[$locationID] = <<<ELEM
<a class="weather_reading" href="/measurement/{$readingID}">
    <img class="icon" src="{$reading['icon']}" alt="icon for {$reading['short_description']}"/>
    <div class="temperature">{$reading['temperature']}&deg;C</div>
    <div class="humidity">{$reading['humidity']}%</div>
    <div class="short_description">{$reading['short_description']}</div>
    <div class="comments button">${reading['comments']} comments</div>
</a>

ELEM;
                            }
                        }

                        $hoursAgo = 3 * $intervalsAgo;

                        echo "<th>{$hoursAgo} hours ago</th>";
                        foreach ($locations as $id => $location) {
                            if (isset($rowElements[$id])) {
                                echo "<td>$rowElements[$id]</td>";
                            } else {
                                echo "<td>No data</td>";
                            }
                        }

                        echo "</tr>";
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </body>
</html>
